In [1]:
from IPython.display import display, HTML 
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<b><font size="5" color="red">ch05. 함수 </font></b>
# 1절. BeautifulSoup과 parser
```pip install bs4 ``` 아나콘다 설치하면 7500여개의 패키지 설치 중 하나
- 공식 사이트 : https://www.crummy.com/software/BeautifulSoup/
- Docs : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [2]:
import requests # HTTP 요청 처리 lib
from requests_file import FileAdapter

In [3]:
s = requests.Session() # HTTP 요청관리를 위한 세션 객체
s.mount("file://", FileAdapter())
response = s.get('file:///ksmindpks/ai_x/source/01_python/ch14_sample.html')
response

In [4]:
response.status_code
# 200: 정상, 404: 없는 페이지, 406: get.post 오류

200

In [5]:
response.content # 바이너리 형식의 내용

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [6]:
response.content.decode('utf-8')

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [7]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [8]:
# html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content,  # response.text
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
</head>
<body>
<h1 class="greeting css" id="text">Hello, CSS</h1>
<h1 class="css">Hi, CSS</h1>
<div id="subject">subject 선택자 안의 내용</div>
<p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
<div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
<div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [13]:
# soup.select_one('선택자') : 해당 선택자 처음 하나만
el = soup.select_one('h1') # 처음 나오는 h1태그 하나만
print('el :', el)
print('el.text :', el.text)
print('el.string :', el.string)
#print('el의 속성들 :', el.attrs)
#print('el의 title속성 :', el.attrs['title'])
#print('el의 title속성 :', el.attrs.get('title') )
print('el의 이름 :', el.name)

el : <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text : Hello, CSS
el.string : Hello, CSS
el의 이름 : h1

In [15]:
# soup.select('선택자') : 해당 선택자 모든 엘리먼트를 리스트로
el = soup.select('h1')
print('리스트 el :', el)
print('el의 text들 :', [e.text for e in el])
for e in el:
    print(e.text, end=',')
print('\n')
print('el의 속성들 :', [e.attrs for e in el])
print('el의 class속성들 :', [e.attrs.get('class') for e in el])

리스트 el : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
el의 text들 : ['Hello, CSS', 'Hi, CSS']
Hello, CSS,Hi, CSS,

el의 속성들 : [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
el의 class속성들 : [['greeting', 'css'], ['css']]

In [16]:
# select_one(선택자)와 find(태그, 속성)
print('select_one :', soup.select_one('h1.css'))
print('find :', soup.find('h1', {'class':'css'}))
print('find :', soup.find('h1', class_='css'))
print()
print('select_one :', soup.select_one('h1#text'))
print('find :', soup.find('h1', {'id':'text'}));

select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>
find : <h1 class="greeting css" id="text">Hello, CSS</h1>
find : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>
find : <h1 class="greeting css" id="text">Hello, CSS</h1>

In [17]:
# 없는 엘리먼트 찾기
print('find_all(빈list) :', soup.find_all('a', class_='css'))
print('find(None) :', soup.find('a', class_='css'))
print('select(빈list) :', soup.select('a.css'))
print('select_one(None) :', soup.select_one('a.css'))

find_all(빈list) : []
find(None) : None
select(빈list) : []
select_one(None) : None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
- json, html, xml
## 2.1 JSON파일
- request모듈(get)
- urllib.request모듈(urlopen)

In [18]:
# 크롤링 허용 범위는 사이트마다 ~/robots.txt에서 확인 할 수 있습니다

In [19]:
# 방법1
import requests
response = requests.get('http://api.github.com')
response, response.status_code

(<Response [200]>, 200)

In [20]:
# 방법2
from urllib.request import urlopen
response = urlopen('http://api.github.com')
response

In [21]:
text = '{"속성1": "값1","속성2":"값2"}'
type(text)

str

In [22]:
# 문자(딕셔너리 타입)를 딕셔너리
# '{"속성1": "값1","속성2":"값2"}' => {"속성1": "값1","속성2":"값2"}
import json
json.loads(text)

{'속성1': '값1', '속성2': '값2'}

## 2.2 html 파일
### 1) 환율정보 가져오기 (네이버 -> 증권 -> 시장지표)
 - https://finance.naver.com/marketindex/

In [24]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex'
response = requests.get(url)
response, response.status_code

(<Response [200]>, 200)

In [26]:
response.content

b'\n<script language=javascript src="/template/head_js.naver?referer=info.finance.naver.com&menu=marketindex&submenu=market"></script>\n<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20250522145100/js/info/jindo.min.ns.1.5.3.euckr.js"></script>\n<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20250522145100/js/jindo.1.5.3.element-text-patch.js"></script>\n\n\n\t\n\t\n\t<div id="container" style="padding-bottom:0px;">\n\t\n\n\t\t\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\t<div class="market_include">\n\t<div class="market_data">\n\t\t<div class="market1">\n\t\t\t<div class="title">\n\t\t\t\t<h2 class="h_market1"><span>\xc8\xaf\xc0\xfc \xb0\xed\xbd\xc3 \xc8\xaf\xc0\xb2</span></h2>\n\t\t\t</div>\n\t\t\t<!-- data -->\n\t\t\t<div class="data">\n\t\t\t\t<ul class="data_lst" id="exchangeList">\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="on">\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" class="head usd" onClick="clickcr(this, \'fr1.usdt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xb9\xcc\xb1\xb9 USD</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">1,375.60</span>\n\t\t\t\t\t\t\t<span class="txt_krw"><span class="blind">\xbf\xf8</span></span>\n\t\t\t\t\t\t\t<span class="change"> 0.40</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" class="graph_img" onClick="clickcr(this, \'fr1.usdc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDKRW.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28 22:05</span>\n\t\t\t\t\t\t<span class="source">\xc7\xcf\xb3\xaa\xc0\xba\xc7\xe0 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t<span class="count">\xb0\xed\xbd\xc3\xc8\xb8\xc2\xf7<span class="num">1253</span>\xc8\xb8</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="">\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" class="head jpy" onClick="clickcr(this, \'fr1.jpyt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xc0\xcf\xba\xbb JPY(100\xbf\xa3)</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">949.51</span>\n\t\t\t\t\t\t\t<span class="txt_krw"><span class="blind">\xbf\xf8</span></span>\n\t\t\t\t\t\t\t<span class="change"> 4.82</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" class="graph_img" onClick="clickcr(this, \'fr1.jpyc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_JPYKRW.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28 22:05</span>\n\t\t\t\t\t\t<span class="source">\xc7\xcf\xb3\xaa\xc0\xba\xc7\xe0 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t<span class="count">\xb0\xed\xbd\xc3\xc8\xb8\xc2\xf7<span class="num">1253</span>\xc8\xb8</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="">\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" class="head eur" onClick="clickcr(this, \'fr1.eurt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xc0\xaf\xb7\xb4\xbf\xac\xc7\xd5 EUR</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">1,553.33</span>\n\t\t\t\t\t\t\t<span class="txt_krw"><span class="blind">\xbf\xf8</span></span>\n\t\t\t\t\t\t\t<span class="change"> 6.57</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" class="graph_img" onClick="clickcr(this, \'fr1.eurc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURKRW.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28 22:05</span>\n\t\t\t\t\t\t<span class="source">\xc7\xcf\xb3\xaa\xc0\xba\xc7\xe0 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t<span class="count">\xb0\xed\xbd\xc3\xc8\xb8\xc2\xf7<span class="num">1253</span>\xc8\xb8</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="">\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" class="head cny" onClick="clickcr(this, \'fr1.cnyt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xc1\xdf\xb1\xb9 CNY</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">191.25</span>\n\t\t\t\t\t\t\t<span class="txt_krw"><span class="blind">\xbf\xf8</span></span>\n\t\t\t\t\t\t\t<span class="change"> 0.13</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" class="graph_img" onClick="clickcr(this, \'fr1.cnyc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_CNYKRW.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28 22:05</span>\n\t\t\t\t\t\t<span class="source">\xc7\xcf\xb3\xaa\xc0\xba\xc7\xe0 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t<span class="count">\xb0\xed\xbd\xc3\xc8\xb8\xc2\xf7<span class="num">1253</span>\xc8\xb8</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\n\t\t\t\t</ul>\t\t\t\t\n\t\t\t</div>\n\t\t\t<!-- //data -->\n\t\t</div>\n\t\t<div class="market2">\n\t\t\t<div class="title">\n\t\t\t\t<h2 class="h_market2"><span>\xb1\xb9\xc1\xa6 \xbd\xc3\xc0\xe5 \xc8\xaf\xc0\xb2</span></h2>\n\t\t\t</div>\n\t\t\t<!-- data -->\n\t\t\t<div class="data">\n\t\t\t\t\n\t\t\t\t<ul class="data_lst" id="worldExchangeList">\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="on">\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" class="head jpy_usd" onClick="clickcr(this, \'fr2.jpyut\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xb4\xde\xb7\xaf/\xc0\xcf\xba\xbb \xbf\xa3</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_up">\n\t\t\t\t\t\t\t<span class="value">144.8600</span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<span class="txt_jpy"><span class="blind">\xbf\xa3</span></span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t<span class="change">0.4800</span>\n\t\t\t\t\t\t\t<span class="blind">\xbb\xf3\xbd\xc2</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" class="graph_img" onClick="clickcr(this, \'fr2.jpyuc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDJPY.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28</span>\n\t\t\t\t\t\t<span class="source">\xb8\xf0\xb4\xd7\xbd\xba\xc5\xb8 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="">\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" class="head usd_eur" onClick="clickcr(this, \'fr2.eurdt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xc0\xaf\xb7\xce/\xb4\xde\xb7\xaf</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">1.1302</span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<span class="txt_usd"><span class="blind">\xb4\xde\xb7\xaf</span></span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t<span class="change"> 0.0040</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" class="graph_img" onClick="clickcr(this, \'fr2.eurdc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURUSD.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28</span>\n\t\t\t\t\t\t<span class="source">\xb8\xf0\xb4\xd7\xbd\xba\xc5\xb8 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="">\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" class="head usd_gbp" onClick="clickcr(this, \'fr2.gbpdt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xbf\xb5\xb1\xb9 \xc6\xc4\xbf\xee\xb5\xe5/\xb4\xde\xb7\xaf</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">1.3470</span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<span class="txt_usd"><span class="blind">\xb4\xde\xb7\xaf</span></span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t<span class="change"> 0.0050</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" class="graph_img" onClick="clickcr(this, \'fr2.gbpdc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_GBPUSD.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.28</span>\n\t\t\t\t\t\t<span class="source">\xb8\xf0\xb4\xd7\xbd\xba\xc5\xb8 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t    \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \n\t\t\t\t         \t\t\t         \n\t\t\t\t        \n\t\t\t\t\t\n\t\t\t\t \t<li class="">\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" class="head usd_idx" onClick="clickcr(this, \'fr2.indt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xb4\xde\xb7\xaf\xc0\xce\xb5\xa6\xbd\xba</span></h3>\n\t\t\t\t\t\t\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_up">\n\t\t\t\t\t\t\t<span class="value">99.4200</span>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t<span class="change">0.4100</span>\n\t\t\t\t\t\t\t<span class="blind">\xbb\xf3\xbd\xc2</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" class="graph_img" onClick="clickcr(this, \'fr2.indc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDX.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t<span class="time">2025.05.27</span>\n\t\t\t\t\t\t<span class="source">ICE \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t</ul>\t\t\t\t\t\t\t\t\n\t\t\t</div>\n\t\t\t<!-- //data -->\n\t\t</div>\n\t\t<div class="market3">\n\t\t\t<div class="title">\n\t\t\t\t<h2 class="h_market3"><span>\xc0\xaf\xb0\xa1&middot;\xb1\xdd\xbd\xc3\xbc\xbc</span></h2>\n\t\t\t</div>\n\t\t\t<!-- data -->\n\t\t\t<div class="data">\n\t\t\t\t\n\t\t\t\t<ul class="data_lst" id="oilGoldList">\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t    \n\t\t\t\t\t\t\n\t\t\t\t\t    \t\n\t\t\t\t\t<li class="on">\n   \t\t\t\t   \t<a href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&fdtc=2" class="head wti" onClick="clickcr(this, \'fr3.wtit\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">WTI</span></h3>\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">60.89</span>\n\t\t\t\t\t\t\t<span class="txt_usd"><span class="blind">\xb4\xde\xb7\xaf</span></span>\n\t\t\t\t\t\t\t<span class="change"> 0.64</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&fdtc=2" class="graph_img" onClick="clickcr(this, \'fr3.wtic\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_CL.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t\t<span class="time">2025.05.27</span>\n\t\t\t\t\t\t\t<span class="source">NYMEX(\xb4\xba\xbf\xe5\xbb\xf3\xbe\xf7\xb0\xc5\xb7\xa1\xbc\xd2) \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t    \n\t\t\t\t\t\t\n\t\t\t\t\t    \t\n\t\t\t\t\t<li class="">\n   \t\t\t\t   \t<a href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" class="head gasoline" onClick="clickcr(this, \'fr3.oilt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xc8\xd6\xb9\xdf\xc0\xaf</span></h3>\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">1632.87</span>\n\t\t\t\t\t\t\t<span class="txt_krw"><span class="blind">\xbf\xf8</span></span>\n\t\t\t\t\t\t\t<span class="change"> 0.78</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" class="graph_img" onClick="clickcr(this, \'fr3.oilc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_GSL.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t\t<span class="time">2025.05.28</span>\n\t\t\t\t\t\t\t<span class="source">\xc7\xd1\xb1\xb9\xbc\xae\xc0\xaf\xb0\xf8\xbb\xe7 Opinet \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t    \n\t\t\t\t\t\t\n\t\t\t\t\t    \t\n\t\t\t\t\t<li class="">\n   \t\t\t\t   \t<a href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&fdtc=2" class="head gold_inter" onClick="clickcr(this, \'fr3.agoldt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xb1\xb9\xc1\xa6 \xb1\xdd</span></h3>\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">3300.4</span>\n\t\t\t\t\t\t\t<span class="txt_usd"><span class="blind">\xb4\xde\xb7\xaf</span></span>\n\t\t\t\t\t\t\t<span class="change"> 65.40</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&fdtc=2" class="graph_img" onClick="clickcr(this, \'fr3.agoldc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GC.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t\t<span class="time">2025.05.27</span>\n\t\t\t\t\t\t\t<span class="source">COMEX(\xb4\xba\xbf\xe5\xbb\xf3\xc7\xb0\xb0\xc5\xb7\xa1\xbc\xd2) \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t    \n\t\t\t\t\t\t\n\t\t\t\t\t    \t\n\t\t\t\t\t<li class="">\n   \t\t\t\t   \t<a href="/marketindex/goldDetail.naver" class="head gold_domestic" onClick="clickcr(this, \'fr3.kgoldt\', \'\', \'\', event);">\n\t\t\t\t\t\t<h3 class="h_lst"><span class="blind">\xb1\xb9\xb3\xbb \xb1\xdd</span></h3>\n\t\t\t\t\t\t \n\t\t\t\t\t\t\n\t\t\t\t         \t\n\t\t\t\t         \t\n\t\t\t\t         \t\t\t\t\t         \t\t\t         \n\t\t\t\t     \t    \n\t\t\t\t\t\t<div class="head_info point_dn">\n\t\t\t\t\t\t\t<span class="value">145688.4</span>\n\t\t\t\t\t\t\t<span class="txt_krw"><span class="blind">\xbf\xf8</span></span>\n\t\t\t\t\t\t\t<span class="change"> 295.49</span>\n\t\t\t\t\t\t\t<span class="blind">\xc7\xcf\xb6\xf4</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<a href="/marketindex/goldDetail.naver" class="graph_img" onClick="clickcr(this, \'fr3.kgoldc\', \'\', \'\', event);">\n\t\t\t\t\t\t<img src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GD.png" alt="" width="295" height="153">\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t<div class="graph_info">\n\t\t\t\t\t\t\t<span class="time">2025.05.28 23:59</span>\n\t\t\t\t\t\t\t<span class="source">\xbd\xc5\xc7\xd1\xc0\xba\xc7\xe0 \xb1\xe2\xc1\xd8</span>\n\t\t\t\t\t\t\t(<span class="num">453</span>\xc8\xb8\xc2\xf7)\t\t\t\n\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t</li>\n\t\t\t\t\n\t\t\t\t</ul>\t\t\t\t\t\t\t\t\n\t\t\t</div>\n\t\t\t<!-- //data -->\n\t\t</div>\n\t</div>\n</div>\t\n<div id="content" class="marketindex_content _replaceNewsLink">\n\t<div class="section_news">\n\t\t<h3 class="h_market"><span>\xc8\xaf\xc0\xb2

In [27]:
response.content.decode('cp949') == response.text

True

In [28]:
soup = BeautifulSoup(response.text, # response.content
                    'html.parser')

In [29]:
# 방법2
from urllib.request import urlopen
response = urlopen(url)
# response.status 상태코드
# response.read()
# response.read().decode('cp949')
soup = BeautifulSoup(response,  # response.read()
                     'html.parser')

In [30]:
title = soup.select('h3.h_lst > span.blind')
for t in title:
    print(t.text, end='\t')

미국 USD	일본 JPY(100엔)	유럽연합 EUR	중국 CNY	달러/일본 엔	유로/달러	영국 파운드/달러	달러인덱스	WTI	휘발유	국제 금	국내 금

In [31]:
price = soup.select('div.head_info > span.value')
[p.text for p in price]
[round(float(p.text.replace(',',''))) for p in price]
[round(float(''.join(p.text.split(',')))) for p in price]

[1375, 949, 1553, 191, 145, 1, 1, 99, 61, 1633, 3300, 145688]

In [32]:
out = '1,374.70'
round(float(''.join(out.split(','))))

1375

In [33]:
round(float(out.replace(',','')))

1375

In [34]:
unit = soup.select('div.head_info > span > span.blind')
unit = [u.text for u in unit]
unit.insert(7, '') # 7번째 index에 '' 추가
unit

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [36]:
status = soup.select('div.head_info > span.blind')
[t.text for t in title]
[p.text for p in price]
unit
[s.string for s in status]

['하락', '하락', '하락', '하락', '상승', '하락', '하락', '상승', '하락', '하락', '하락', '하락']

In [37]:
len(title), len(price), len(unit), len(status)

(12, 12, 12, 12)

In [38]:
for idx in range(len(title)):
    print("{}. {} : {}{} - {}".format(idx+1,
                                     title[idx].text,
                                     price[idx].text,
                                     unit[idx],
                                     status[idx].text))

1. 미국 USD : 1,375.00원 - 하락
2. 일본 JPY(100엔) : 948.90원 - 하락
3. 유럽연합 EUR : 1,552.58원 - 하락
4. 중국 CNY : 191.15원 - 하락
5. 달러/일본 엔 : 144.8600엔 - 상승
6. 유로/달러 : 1.1302달러 - 하락
7. 영국 파운드/달러 : 1.3470달러 - 하락
8. 달러인덱스 : 99.4200 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1632.87원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 145688.4원 - 하락

In [39]:
for t, p, u, s  in zip(title, price, unit, status):
    print("{} : {}{} - {}".format(t.text,
                                 p.text,
                                 u,
                                 s.text))

미국 USD : 1,375.00원 - 하락
일본 JPY(100엔) : 948.90원 - 하락
유럽연합 EUR : 1,552.58원 - 하락
중국 CNY : 191.15원 - 하락
달러/일본 엔 : 144.8600엔 - 상승
유로/달러 : 1.1302달러 - 하락
영국 파운드/달러 : 1.3470달러 - 하락
달러인덱스 : 99.4200 - 상승
WTI : 60.89달러 - 하락
휘발유 : 1632.87원 - 하락
국제 금 : 3300.4달러 - 하락
국내 금 : 145688.4원 - 하락

In [40]:
for idx, (t, p, u, s)  in enumerate(zip(title, price, unit, status)):
    print("{}. {} : {}{} - {}".format(idx+1,
                                t.text,
                                p.text,
                                u,
                                s.text))

1. 미국 USD : 1,375.00원 - 하락
2. 일본 JPY(100엔) : 948.90원 - 하락
3. 유럽연합 EUR : 1,552.58원 - 하락
4. 중국 CNY : 191.15원 - 하락
5. 달러/일본 엔 : 144.8600엔 - 상승
6. 유로/달러 : 1.1302달러 - 하락
7. 영국 파운드/달러 : 1.3470달러 - 하락
8. 달러인덱스 : 99.4200 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1632.87원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 145688.4원 - 하락

### 2) 이번주 로또번호 출력
- https://dhlottery.co.kr/gameResult.do?method=byWin (google에 "로또번호 당첨번호" 검색)

    1173회(2025년 05월 24일 추첨)
    당첨번호 [1 5 18 20 30 35]
    보너스 3

In [41]:
# 방법1의 soup객체 생성
import requests
from bs4 import BeautifulSoup
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = requests.get(url)
soup = BeautifulSoup(response.content, # response.text
                    "html.parser")

In [42]:
# 방법2의 sou객체 생성
from urllib.request import urlopen
response = urlopen(url)
soup = BeautifulSoup(response, "html.parser")

In [43]:
times = soup.select_one('div.win_result > h4 > strong').text # 1173회
date = soup.select_one('div.win_result >p.desc').text  #(2025년 05월 24일 추첨)
print(times, date)
title1 = soup.select_one('div.num.win > strong').text
lotto_number = soup.select('div.num.win > p > span')
print(title1, [int(lotto.text) for lotto in lotto_number])
title2 = soup.select_one('div.num.bonus > strong').string
bonus_number = soup.select_one('div.num.bonus > p > span').text
print(title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

In [44]:
# 위의 select 함수를 find함수로
#times = soup.select_one('div.win_result > h4 > strong').text # 1173회
win_result = soup.find('div', class_="win_result")
times = win_result.find('strong').text
# date = soup.select_one('div.win_result >p.desc').text  #(2025년 05월 24일 추첨)
date = soup.find('p', class_='desc').text
print(times, date)
# title1 = soup.select_one('div.num.win > strong').text
num_win = soup.find('div', class_=['win'])
title1 = num_win.find('strong').text
# lotto_number = soup.select('div.num.win > p > span')
lotto_number = num_win.find_all('span') # 배열
print(title1, [int(lotto.text) for lotto in lotto_number])
# title2 = soup.select_one('div.num.bonus > strong').string
num_bonus = soup.find('div', class_=['bonus'])
title2 = num_bonus.find('strong').text
# bonus_number = soup.select_one('div.num.bonus > p > span').text
bonus_number = num_bonus.find('span').text
print(title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

### 3) 다음 검색 리스트
    no  title   link
    0 [비트코인 2025] 백악관 크립토 차르~ https://v.daum.net/v/20250528103907230
    1 [비즈 나우] 비트코인 2025 컨퍼런~   https://v.daum.net/v/20250528075215864
    ...

In [45]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색한 결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
import pandas as pd
pd.DataFrame(items_find_list)

,no,title,link
0,0,막 오른 미국 최대 비트코인 행사…시장 영향은,http://v.daum.net/v/20250529050024694
1,1,"밴스 “가상 화폐, 이미 美경제 주류… 1억명 비트코인 보유 시대 온다”",http://v.daum.net/v/20250529041606215
2,2,"미, 연금으로 비트코인 투자 허용...트럼프 일가 혜택 보나",http://v.daum.net/v/20250529044500460
3,3,"코인 폭등, FOMO를 느낀다면 생각해보아야 할 질문들[비트코인 A to Z]",http://v.daum.net/v/20250529060109947
4,4,"美 백악관 '크립토 차르' ""비트코인 추가매입 검토""",http://v.daum.net/v/20250528175702209
5,5,"[글로벌 비즈 브리핑] 백악관 떠나더니…머스크, 트럼프 '작심비판' 外",http://v.daum.net/v/20250529043902386
6,6,[비트코인 2025] JD밴스 “크립토는 이미 美 경제 주류…법·규제 정비해 완전...,http://v.daum.net/v/20250529031200129
7,7,"'밈주식' 대명사 게임스톱, 비트코인 첫 매수…스트래티지 따라하기?",http://v.daum.net/v/20250529042100220
8,8,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
9,9,"<단독>""예배 참석하면 코인 드려요. 5년 안에 비트코인 넘어섭니다""..신앙심 노...",http://v.daum.net/v/20250528083323774

In [46]:
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색한 결과를 담을 2차원 리스트
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs.get('href')])
# items_find_list
import pandas as pd
pd.DataFrame(items_find_list, columns=['no', 'title', 'link'])

,no,title,link
0,0,막 오른 미국 최대 비트코인 행사…시장 영향은,http://v.daum.net/v/20250529050024694
1,1,"밴스 “가상 화폐, 이미 美경제 주류… 1억명 비트코인 보유 시대 온다”",http://v.daum.net/v/20250529041606215
2,2,"미, 연금으로 비트코인 투자 허용...트럼프 일가 혜택 보나",http://v.daum.net/v/20250529044500460
3,3,"코인 폭등, FOMO를 느낀다면 생각해보아야 할 질문들[비트코인 A to Z]",http://v.daum.net/v/20250529060109947
4,4,"美 백악관 '크립토 차르' ""비트코인 추가매입 검토""",http://v.daum.net/v/20250528175702209
5,5,"[글로벌 비즈 브리핑] 백악관 떠나더니…머스크, 트럼프 '작심비판' 外",http://v.daum.net/v/20250529043902386
6,6,[비트코인 2025] JD밴스 “크립토는 이미 美 경제 주류…법·규제 정비해 완전...,http://v.daum.net/v/20250529031200129
7,7,"'밈주식' 대명사 게임스톱, 비트코인 첫 매수…스트래티지 따라하기?",http://v.daum.net/v/20250529042100220
8,8,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
9,9,"<단독>""예배 참석하면 코인 드려요. 5년 안에 비트코인 넘어섭니다""..신앙심 노...",http://v.daum.net/v/20250528083323774

In [47]:
# 다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
keyword = '비트코인'
page = 2
# url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&q={keyword}&p={page}'
# response = requests.get(url)
url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
params = {'q':keyword, 'p':page}
response = requests.get(url, params=params)
soup = BeautifulSoup(response.text,  # response.content
                    'html.parser')
items_find_list = [] # 검색한 결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no': (page-1)*10 + idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    print({'no': (page-1)*10 + idx,
           'title': item.text,
           'link': item.attrs['href']})

{'no': 10, 'title': ' “이래도 안 사?”...‘부자아빠’ 기요사키가 또 추천한 이것 ', 'link': 'http://v.daum.net/v/20250528170905045'}
{'no': 11, 'title': ' 트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고 ', 'link': 'http://v.daum.net/v/20250528084245020'}
{'no': 12, 'title': ' [외신 헤드라인] 엔비디아, 1분기 매출·순익 모두 전망치 상회 ', 'link': 'http://v.daum.net/v/20250529062422262'}
{'no': 13, 'title': ' 게임스탑, 스트래티지 따라하기…비트코인 첫 매수 ', 'link': 'http://v.daum.net/v/20250528221301500'}
{'no': 14, 'title': " '밈주식' 대명사 게임스톱, 비트코인 투자기업으로 변신 ", 'link': 'http://v.daum.net/v/20250528234636597'}
{'no': 15, 'title': ' “맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터] ', 'link': 'http://v.daum.net/v/20250528143002735'}
{'no': 16, 'title': ' [투데이 窓]가상자산 거래에 세제 정비 필요하다 ', 'link': 'http://v.daum.net/v/20250529020502861'}
{'no': 17, 'title': " 숨 고르는 비트코인, 10만8000달러선 '주춤' ", 'link': 'http://v.daum.net/v/20250528095921258'}
{'no': 18, 'title': ' 밴스 부통령 “스테이블코인은 달러와 경제력 높이는 힘” ', 'link': 'http://v.daum.net/v/20250529055702742'}
{'no': 19, 'title': ' 美 상원의원 "트럼프 대통령, 비트코인법 지지" ', 'link': 'http://v.daum.net/v/20250528090342853'}

In [48]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text,  # response.content
                    'html.parser')
    items_find_list = [] # 검색한 결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no': (page-1)*10 + idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    return items_find_list

In [49]:
collect_list('청바지',2)

[{'no': 10,
  'title': " '45kg' 윤은혜, 청바지가 헐렁…'40세' 비현실적 자기관리 끝판왕 ",
  'link': 'http://v.daum.net/v/20250513174826265'},
 {'no': 11,
  'title': ' 손담비, 출산 한 달도 안 됐는데 외출…청바지 폼 애엄마 맞나 ',
  'link': 'http://v.daum.net/v/20250506171902866'},
 {'no': 12,
  'title': ' 네포 베이비, 소피아 리치 그레인지가 청바지를 입는 방법 ',
  'link': 'http://v.daum.net/v/20250509182459873'},
 {'no': 13,
  'title': ' 173㎝ 장원영 맵시 美쳤네, 청바지 하나 입었을 뿐인데 [스타화보] ',
  'link': 'http://v.daum.net/v/20250522115656470'},
 {'no': 14,
  'title': ' [리빙포인트] 무릎 튀어나온 청바지엔 소주 ',
  'link': 'http://v.daum.net/v/20250521002847303'},
 {'no': 15,
  'title': ' 48세 김희선, 흰 셔츠+청바지 기본템 입었을 뿐인데‥미모 레전드 ',
  'link': 'http://v.daum.net/v/20250511134648392'},
 {'no': 16,
  'title': ' 윤은혜, 40세 맞아?…청바지도 헐렁한 극세사 몸매+동안 미모 ',
  'link': 'http://v.daum.net/v/20250515063005066'},
 {'no': 17,
  'title': ' “브래지어에 청바지만”…20년만에 속옷 모델 된 추성훈 아내 야노 시호 ‘파격’ ',
  'link': 'http://v.daum.net/v/20250515195400237'},
 {'no': 18,
  'title': ' ‘청바지’ 입은 안철수 ‘학식’ 이준석 쫓아갔지만 ',
  'link': 'http://v.daum.net/v/20250521160401791'},
 {'no': 19,
  'title': " 서현, '4000m' 알프스 만년설 배경으로 '찰칵'…후드티+청바지로도 빛나는 미모 ",
  'link': 'http://v.daum.net/v/20250519055004613'}]

In [50]:
# 원하는 keyword로 다음검색
result = []
keyword = "청바지"
pages = 4
for page in range(1, pages+1):
    result.extend(collect_list(keyword, page))
    time.sleep(3)
result_df = pd.DataFrame(result)
result_df.head()

,no,title,link
0,0,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
1,1,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
2,2,"'이병헌♥'이민정, 남다른 쇼핑 클래스…청바지 사는데 매장 통째로 빌려 (MJ)",http://v.daum.net/v/20250527202911484
3,3,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
4,4,"'의사 그만둔' 고윤정, 흰 티+청바지...""정석 미녀"" [★해시태그]",http://v.daum.net/v/20250522182007490

In [51]:
keywords = ['청바지','면바지']
pages = 2
result0 = [] # 청바지 검색결과 50개
result1 = [] # 면바지 검색결과 50개
for i, keyword in enumerate(keywords):
    for page in range(1, pages+1):
        print(f'~ ~ ~ {i}번째 {keyword} {page} 검색 중입니다 ~ ~ ~')
        if i==0:
            result0.extend(collect_list(keyword, page))
        else:
            result1.extend(collect_list(keyword, page))
        time.sleep(4)

~ ~ ~ 0번째 청바지 1 검색 중입니다 ~ ~ ~
~ ~ ~ 0번째 청바지 2 검색 중입니다 ~ ~ ~
~ ~ ~ 1번째 면바지 1 검색 중입니다 ~ ~ ~
~ ~ ~ 1번째 면바지 2 검색 중입니다 ~ ~ ~

In [52]:
result0_df = pd.DataFrame(result0)
result0_df.head()

,no,title,link
0,0,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
1,1,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
2,2,"'이병헌♥'이민정, 남다른 쇼핑 클래스…청바지 사는데 매장 통째로 빌려 (MJ)",http://v.daum.net/v/20250527202911484
3,3,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
4,4,"'의사 그만둔' 고윤정, 흰 티+청바지...""정석 미녀"" [★해시태그]",http://v.daum.net/v/20250522182007490

In [53]:
result1_df = pd.DataFrame(result1)
result1_df.head()

,no,title,link
0,0,사천에서 쾌청한 날씨 속 탁 트인 남해 풍경 즐겨요!,http://v.daum.net/v/20250528104429529
1,1,"윤승아, ♥김무열 쏙 빼닮은 깜찍 子 하객룩 공개‥벌써 우월한 유전자",http://v.daum.net/v/20250526145941690
2,2,"""나는 젊어"" 팔소매 접은 이준석의 '흰셔츠' 속에도 뼈가 담겼다[21대 대선 리...",http://v.daum.net/v/20250525070013619
3,3,"이재명, 첫 대학 방문…이준석 겨냥?",http://v.daum.net/v/20250526191942751
4,4,"이번 주 포천 여행,반팔 하나로 충분할까?",http://v.daum.net/v/20250527171732518

In [54]:
result0_df.to_csv('data/ch14_'+keywords[0]+'.csv', index=False, encoding='cp949')
result1_df.to_csv('data/ch14_'+keywords[1]+'.csv', index=False)

### 4) User-agent를 추가하여 크롤링
- urlopen()함수를 사용하면 크롤링이 안되는 사이트
- User-agent를 추가하여 크롤링

In [55]:
# 방법2
from urllib.request import urlopen, Request
import urllib.parse
word = '비트코인'
word = urllib.parse.quote(word)
# print(word)
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
# User-Agent를 추가하여 브라우저처럼 보이게 포장
headers = {'user-agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)
response = urlopen(request)
soup = BeautifulSoup(response, # response.content
                    "html.parser")
def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text,  # response.content
                    'html.parser')
    items_find_list = [] # 검색한 결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no': (page-1)*10 + idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    return items_find_list
collect_list("청바지", 1)

[{'no': 0,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 1,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 2,
  'title': " '이병헌♥'이민정, 남다른 쇼핑 클래스…청바지 사는데 매장 통째로 빌려 (MJ) ",
  'link': 'http://v.daum.net/v/20250527202911484'},
 {'no': 3,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 4,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 7,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 8,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'},
 {'no': 9,
  'title': ' 60대인데요, 청바지를 다시 입었습니다 ',
  'link': 'http://v.daum.net/v/20250430145405823'}]

In [56]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
melonpage = requests.get(url)
melonpage.status_code

406

In [57]:
# 방법2
from urllib.request import urlopen, Request
# melonpage = urlopen(url) 에러남

In [58]:
# User-Agent 추가
headers = {'user-agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
}
# 방법2
request = Request(url, headers=headers)
melonpage = urlopen(request)
# 방법1
melonpage = requests.get(url, headers=headers)
soup = BeautifulSoup(melonpage.text, # melonpage.content
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<title>멜론차트&gt;TOP100&gt;멜론</title>
<meta content="음악서비스, 멜론차트, 멜론TOP100, 최신음악, 인기가요, 뮤직비디오, 앨범, 플레이어, 스트리밍, 다운로드, 아티스트플러스, 아티스트채널" name="keywords"/>
<meta content="No.1 뮤직플랫폼 멜론! 최신 트렌드부터 나를 아는 똑똑한 음악추천까지!" name="description"/>
<meta content="ee85ff6db1fa8f2226bcb671ecb2bcdbcffb6f8b" name="naver-site-verification"/>
<meta content="q4tbTQhmxa4La3OdNLsNOCxrJ_WV6lUlBFrFW4-HqQc" name="google-site-verification"/>
<meta content="4022717807957185" property="fb:app_id"/>
<meta content="Melon" property="og:title"/>
<meta content="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" property="og:image"/>
<meta content="음악이 필요한 순간, 멜론" property="og:description"/>
<meta content="http://www.melon.com/chart/" property="og:url"/>
<meta content="website" property="og:type"/>
<meta content="멜론" property="og:site_name"/>
<meta content="width=device-width" name="viewport"/>
<link href="/favicon.ico?2" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/9d/x/e9gkymzs.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/l8/i/bmqlrmeyi7uljr5.css" rel="stylesheet" type="text/css"/>
<!-- 댓글 css 파일 네임 변경 -->
<link href="https://static.melon.co.kr/static/web/resource/style/w1/dn/4/ynesuqe51i.css" rel="stylesheet" type="text/css"/>
<link href="/resource/style/web/chart/melonweb_chart_4x.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/qa/5/rlbqwv6hljdyw.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400" rel="stylesheet"/>
<script src="/resource/script/cds/common/web/member_api.js" type="text/javascript"></script>
<script src="/resource/script/cds/common/web/commerce_api.js" type="text/javascript"></script>
<script src="/resource/script/web/common/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="https://member.melon.com/resource/script/web/member/melonweb_member_external.js?tm=20250529" type="text/javascript"></script>
<script src="https://static.melon.co.kr/static/web/resource/script/w1/c1/d/7j9pwitvgh7.js" type="text/javascript"></script>
<script type="text/javascript">
	(function() {
		WEBPOCIMG = {
			defaultImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				var thumbType = "_500";
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultAlbumImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultArtistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultDjImg : function(obj){
			},
			defaultMvImg : function(obj, width, height){
				if(width == null || width == '') width = $(obj).width();
				if(height == null || height == '') height = $(obj).height();

				var ratio43 = Math.floor((4/3)*10)/10;
				var ratio169 = Math.floor((16/9)*10)/10;
				var ratioObj = Math.floor((width/height)*10)/10;

				var ratio = "4x3";
				if(ratioObj == ratio43){
					ratio = "4x3"; //contentsType = "mv43";
				} else if(ratioObj == ratio169){
					ratio = "16x9"; //contentsType = "mv169";
				} else {
					if(ratioObj > 1.5) ratio = "16x9";
					else ratio = "4x3";
				}

				if(width == 0) width = 640;
				if(height == 0) ratio = "16x9";

				//가장 큰사이즈로 리사이즈함
				var thumbType = "_" + ratio + "_640";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noMovie" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPlaylistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultMemberImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPhotoImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShopImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 256;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_256";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noProduct" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShowwingImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noShowing" + thumbType + ".jpg";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultTicketImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noTicket" + thumbType + ".png";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultSmartRadioImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noSmartradio_59_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultConcertImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum_114_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			}
		}
		,WEBELLIPSIS = {
			ellipsis : function(ellipsisName,moreClassName,eWidth){
		        //아티스트 더보기
		        var arObj = $('.' + ellipsisName);
		        for(var i = 0; i < arObj.length; i++){
		            if (arObj.eq(i).width() > eWidth ){
		                arObj.eq(i).parent().parent().parent().find('.' + moreClassName).show();
		            }
		        }
			}
		}
	})();
	</script>
</head>
<body>
<div id="wrap">
<div id="skip_nav">skip navigation
		<ul>
<li><a href="#gnb_menu">메뉴</a></li>
<li><a href="#conts_section">본문</a></li>
<li><a href="#footer">하단 정보</a></li>
</ul>
</div>
<!--  header -->
<div class="gnb2_expn" id="header">
<div class="my_fold" id="header_wrap"> <!-- 1024이상 마이영역 접었을때 클래스 my_fold 추가 -->
<div class="clfix" id="gnb">
<!-- 상단 빠른 메뉴 -->
<div id="util_menu">
<p class="none">상단 빠른 메뉴</p>
<div class="top_left">
<ul class="clfix">
<li class="first_child d_melon_ticket"><a class="menu01 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V08&amp;ACTION_AF_CLICK=V1" href="//ticket.melon.com/main/index.htm" title="멜론 티켓"><span>멜론 티켓</span></a></li>
</ul>
</div>
<!-- 140603_수정 -->
<div class="top_right">
<ul class="clfix">
<li class="first_child"><a class="menu01 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B01&amp;ACTION_AF_CLICK=V1" href="/commerce/pamphlet/web/sale_listMainView.htm" title="이용권구매"><span>이용권구매</span></a></li>
<li><a class="menu02 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V06&amp;ACTION_AF_CLICK=V1" href="/event/vip/index.htm" title="멜론라운지"><span>멜론라운지</span></a></li>
<li><a class="menu03 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B03&amp;ACTION_AF_CLICK=V1" href="/event/list.htm" title="이벤트"><span>이벤트</span></a></li>
<li class="last_child"><a class="menu04 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V02&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/customer/announce/index.htm" title="공지사항"><span>공지사항</span></a></li>
</ul>
<script type="text/javascript">
							var html = '';
							var logoutReturnUrl = window.location.href;

							if(logoutReturnUrl == ''){
								logoutReturnUrl = 'www.melon.com';
							}

							if(isMelonLogin()){

								var memberKey = getMemberKey()
								var memberInfo = svcMember.displayIdByMemberKey(memberKey);
								var memberType = svcMember.getMemberType().MEMBERTYPE;
								var gradeInfo = svcMember.gradeInfoByMemberKey(memberKey);

								var memId = '';
								if(memberType == undefined || memberType == null){
									memberType = '0';
								}

								if(memberInfo.DISPLAYID != undefined || memberInfo.DISPLAYID != null){
									memId = memberInfo.DISPLAYID;
								}

								if(memId.indexOf("@") != -1 && memberType != '1'){//카카오계정이 아닌경우에만 @도메인 영역 삭제처리
									memId = memId.split("@")[0];
								}

								var fromMPS = getCookie("MPS"); // 멜론 플레이어에서 왔는지 확인.
								var fromMPSYn = fromMPS == null || fromMPS.indexOf("MELONPLAYER") < 0;

								var gradeImg = "";
								var gradeName = gradeInfo.GRADE;
								var gradeImageUrl = gradeInfo.HTTPSIMAGEURL;

								if(gradeName == undefined || gradeName == null){
									gradeName = '일반';
								}

								try {

									gradeImageUrl = gradeImageUrl.replace('http:','');

									if(gradeName == '일반'){
										gradeImageUrl = "";
									}

									if(gradeImageUrl != ''){
										gradeImg = "<span class=\"icon_logon\"><img src=\""+gradeImageUrl+"\" width=\"18\" height=\"18\" alt=\""+gradeName+"\" /></span>";
									}
									//카카오연동확인
									if(memberType == '1'){
										gradeImg += '<span class="icon_logon"><img src="//cdnimg.melon.co.kr/resource/image/web/common/icon_kakao.png" width="18" height="18" alt="kakao"></span>';
									}
								} catch (e) {}

								var logoutButtonHtml = '<button type="button" title="로그아웃" class="btn_top_logout" onclick="javascript:MELON.WEBSVC.POC.logout(\'\');"><img src="//cdnimg.melon.co.kr/resource/image/web/common/btn_top_logout.png" width="44" height="12" alt="로그아웃"></button>';

								html = ['<div class="header_login">',
									' <span class="icon_grade">',
									'' + gradeImg + '',
									' </span>',
									' <span class="wrap_id"><a href="javascript:location.href=_getHttpsMemberDomain()+ \'/muid/web/help/myinfointro_inform.htm\';" class="user_id"><strong>' + memId + '</strong></a> 님</span>',
									fromMPSYn ? logoutButtonHtml : '', //멜론 플레이어에서 로그아웃 싱크 안맞는 이슈로 인해 로그아웃 멜론 플레이어에서 왔을 시 버튼 제거
									'</div>'
								].join('');
								document.write(html);
							}
						</script>
</div>
<!-- //140603_수정 -->
</div>
<!-- //상단 빠른 메뉴 -->
<!-- 140603_수정 -->
<h1><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=M01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/index.htm" title="MelOn 로고 - 홈으로 이동"><img alt="Melon" height="99" src="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" width="142"/></a></h1>
<!-- //140603_수정 -->
<!-- 통합검색 영역 -->
<fieldset>
<legend>통합검색영역</legend>
<input id="top_search" name="" onkeypress="if(event.keyCode == 13){goSearch();}" placeholder="" style="width:249px" title="검색 입력 편집창" type="text"/><input id="keywordLink" name="keywordLink" type="hidden" value=""/>
<button class="btn_icon btn_auto close" id="top_search_autocomplete_toggle" style="display: none;" title="자동검색 펼침" type="button"><span class="odd_span">자동검색 펼침</span></button> <!-- open/close 클래스 사용 -->
<button class="btn_icon search_m" title="검색" type="button"><span class="odd_span">검색</span></button>
<div class="auto_complete" id="top_search_autocomplete"><div class="auto_complete_cont" style="display:block;"><!-- 자동완성 레이어 --></div></div>
<div class="auto_complete" id="top_search_autocomplete_template" style="display: none;"> <!-- 자동완성 레이어 템플릿 -->
<!-- 텍스트 결과 -->
<ul class="text_result">
<li><a class="autocomplete-label" href="#"></a></li>
</ul>
<!-- 섬네일 결과 -->
<ul class="thumb_result">
<li class="cate"></li>
<li class="class02">
<a href="#">
<span class="thumb_40">
<span class="thumb_frame"></span>
<img alt="" class="autocomplete-img" height="40" width="40"/>
</span>
<div class="info">
<span class="autocomplete-label"></span><br/>
<span><span class="f11 autocomplete-info"></span></span>
</div>
</a>
</li>
</ul>
<!-- 검색어가 없을 때 -->
<ul class="text_result">
<li class="result_none">
<span>해당글자로 시작하는 단어가 없습니다.</span>
</li>
</ul>
</div>
</fieldset>
<form action="" id="searchFrm" method="get" style="display: none">
<input name="q" type="hidden"/>
<input name="section" type="hidden"/>
</form>
<!-- //통합검색 영역 -->
<!-- 실시간 검색어 -->
<div class="realtime_soar_keyword">
<!-- 140519_수정 -->
<a class="title" href="#none">급상승 키워드</a>
<!-- //140519_수정 -->
<div class="keyword_overlay">
<ol style="overflow:hidden; height:20px;">
</ol>
<!-- 140423_추가 -->
<!-- //140423_추가 -->
</div>
</div>
<!-- //실시간 검색어 -->
<!-- 배너 영역 -->
<div class="cmn_banner"></div>
</div>
<!-- 140314_gnb마크업 수정 -->
<div id="gnb_menu">
<ul>
<li class="nth1 on">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=R01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/chart/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu01">멜론차트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child on"><a href="//www.melon.com/chart/index.htm"><span class="menu_chart m1">TOP100</span></a></li>
<li class=""><a href="//www.melon.com/chart/hot100/index.htm"><span class="menu_chart m6">HOT100</span></a></li><!-- // MELONUIT-2465 -->
<li class=""><a href="//www.melon.com/chart/day/index.htm"><span class="menu_chart m2">일간</span></a></li>
<li class=""><a href="//www.melon.com/chart/week/index.htm"><span class="menu_chart m3">주간</span></a></li>
<li class=""><a href="//www.melon.com/chart/month/index.htm"><span class="menu_chart m4">월간</span></a></li>
<li class=""><a href="//www.melon.com/chart/age/index.htm"><span class="menu_chart m5">시대</span></a></li>
</ul>
<div class="chart_finder">
<button class="btn_chart_f" onclick="location.href='//www.melon.com/chart/search/index.htm'" type="button"><span class="odd_span">차트 파인더</span></button>
</div>
</div>
</li>
<li class="nth2">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/new/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu02">최신 음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/new/index.htm"><span class="menu_new m1">최신곡</span></a></li>
<li class=""><a href="//www.melon.com/new/album/index.htm"><span class="menu_new m2">최신앨범</span></a></li>
<li class=""><a href="//www.melon.com/new/mv/index.htm"><span class="menu_new m3">최신 뮤직비디오</span></a></li>
</ul>
</div>
</li>
<li class="nth3">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C03&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu03">장르 음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="menu_gnr nm1">한국대중음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0900"><span class="menu_gnr nm2">해외POP음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN1500"><span class="menu_gnr nm3">그외 인기장르</span></a></li>
</ul>
</div>
</li>
<li class="nth4">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S04&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/dj/today/djtoday_list.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu04">멜론DJ</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/dj/today/djtoday_list.htm"><span class="menu_dj m1">오늘은 뭘 듣지</span></a></li>
<li class=""><a href="//www.melon.com/dj/essential/djessential_list.htm"><span class="menu_dj m2">전문가 선곡</span></a></li>
<li class=""><a href="//www.melon.com/dj/themegenre/djthemegenre_list.htm"><span class="menu_dj m3">#테마장르</span></a></li>
<li class=""><a href="//www.melon.com/dj/powerdj/djpowerdj_list.htm"><span class="menu_dj m4">파워DJ</span></a></li>
<li class=""><a href="//www.melon.com/dj/chart/djchart_list.htm"><span class="menu_dj m5">인기</span></a></li>
</ul>
</div>
</li>
<li class="nth5">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S05&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/tv/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu05">멜론TV</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/tv/index.htm"><span class="menu_tv m1">오늘은 뭘 볼까</span></a></li>
<li class=""><a href="//www.melon.com/tv/mv/index.htm"><span class="menu_tv m2">뮤직비디오</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=1"><span class="menu_tv m3">멜론 오리지널</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=4"><span class="menu_tv m4">아티스트 업데이트</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=3"><span class="menu_tv m5">방송</span></a></li>
</ul>
</div>
</li>
<li class="nth6">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S07&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu06">스타포스트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="menu_arti m1">NOW</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/artistchart/index.htm"><span class="menu_arti m3">아티스트 랭킹</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/myranking/index.htm"><span class="menu_arti m4">마이 랭킹</span></a></li>
</ul>
<div class="menu_artist_btn">
<div class="artist_fan">
<button class="btn_fan" onclick="MELON.WEBSVC.POC.menu.goMyMusicFanSignArtist();" type="button"><span class="odd_span">팬맺은 아티스트</span></button>
</div>
<div class="artist_finder">

In [59]:
# 멜론 순위, 노래제목, 가수, 좋아요갯수
# 1위 | 너에게 닿기를 | 10cm (100위까지 크롤링)
title_els = soup.select('div.ellipsis.rank01 > span')
singer_els = soup.select('div.ellipsis.rank02 > span.checkEllipsis')
len([title.text.strip() for title in title_els]), \
len([singer.text for singer in singer_els])
for idx, (title, singer) in enumerate(zip(title_els, singer_els)):
    print('{}위 | {} - {}'.format(idx+1,
                                 title.text.strip(),
                                 singer.text))

1위 | 너에게 닿기를 - 10CM
2위 | Never Ending Story - 아이유
3위 | Drowning - WOODZ
4위 | like JENNIE - 제니 (JENNIE)
5위 | 모르시나요(PROD.로코베리) - 조째즈
6위 | TOO BAD (feat. Anderson .Paak) - G-DRAGON
7위 | 네모의 꿈 - 아이유
8위 | Whiplash - aespa
9위 | 나는 반딧불 - 황가람
10위 | HOME SWEET HOME (feat. 태양, 대성) - G-DRAGON
11위 | 어제보다 슬픈 오늘 - 우디 (Woody)
12위 | 오늘만 I LOVE YOU - BOYNEXTDOOR
13위 | REBEL HEART - IVE (아이브)
14위 | HAPPY - DAY6 (데이식스)
15위 | Flower - 오반(OVAN)
16위 | APT. - 로제 (ROSÉ), Bruno Mars
17위 | 빨간 운동화 - 아이유
18위 | 청춘만화 - 이무진
19위 | HOT - LE SSERAFIM (르세라핌)
20위 | 한 페이지가 될 수 있게 - DAY6 (데이식스)
21위 | 10월 4일 - 아이유
22위 | 내게 사랑이 뭐냐고 물어본다면 - 로이킴
23위 | MY LOVE(2025) - 이예은, 아샤트리, 전건호
24위 | Last Scene (Feat. 원슈타인) - 아이유
25위 | 소나기 - 이클립스 (ECLIPSE)
26위 | 천상연 - 이창섭
27위 | THUNDER - 세븐틴 (SEVENTEEN)
28위 | Welcome to the Show - DAY6 (데이식스)
29위 | Die With A Smile - Lady Gaga, Bruno Mars
30위 | toxic till the end - 로제 (ROSÉ)
31위 | Supernova - aespa
32위 | 예뻤어 - DAY6 (데이식스)
33위 | 그날이 오면 - 투모로우바이투게더
34위 | HANDS UP - MEOVV (미야오)
35위 | ATTITUDE - IVE (아이브)
36위 | 미치게 그리워서 - 황가람
37위 | 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 - AKMU (악뮤)
38위 | I DO ME - KiiiKiii (키키)
39위 | DRIP - BABYMONSTER
40위 | 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) - 너드커넥션 (Nerd Connection)
41위 | Love wins all - 아이유
42위 | 청혼하지 않을 이유를 못 찾았어 - 이무진
43위 | 미인 (Feat. Balming Tiger) - 아이유
44위 | 슬픈 초대장 - 순순희(지환)
45위 | PO￦ER - G-DRAGON
46위 | 내 이름 맑음 - QWER
47위 | 주저하는 연인들을 위해 - 잔나비
48위 | 첫 만남은 계획대로 되지 않아 - TWS (투어스)
49위 | UP (KARINA Solo) - aespa
50위 | 고민중독 - QWER
51위 | 너의 모든 순간 - 성시경
52위 | 나는 아픈 건 딱 질색이니까 - i-dle (아이들)
53위 | Fly Up - RIIZE
54위 | 비의 랩소디 - 임재현
55위 | 사랑인가 봐 - 멜로망스
56위 | 에피소드 - 이무진
57위 | Magnetic - 아일릿(ILLIT)
58위 | 모든 날, 모든 순간 (Every day, Every Moment) - 폴킴
59위 | How Sweet - NewJeans
60위 | TAKE ME - G-DRAGON
61위 | 다정히 내 이름을 부르면 - 경서예지, 전건호
62위 | I AM - IVE (아이브)
63위 | 시작의 아이 - 마크툽 (MAKTUB)
64위 | 헤어지자 말해요 - 박재정
65위 | Supersonic - 프로미스나인
66위 | Hype Boy - NewJeans
67위 | The Chase - Hearts2Hearts (하츠투하츠)
68위 | 이렇게 좋아해 본 적이 없어요 - BOYNEXTDOOR
69위 | 인사 - 범진
70위 | 영원해 - 도경수(D.O.)
71위 | 무제(無題) (Untitled, 2014) - G-DRAGON
72위 | Small girl (feat. 도경수(D.O.)) - 이영지
73위 | 사랑은 늘 도망가 - 임영웅
74위 | Seven (feat. Latto) - Clean Ver. - 정국
75위 | Sticky - KISS OF LIFE
76위 | 사막에서 꽃을 피우듯 - 우디 (Woody)
77위 | I Feel Good - BOYNEXTDOOR
78위 | 123-78 - BOYNEXTDOOR
79위 | 취중고백 - 김민석
80위 | 굿데이 2025 (텔레파시 + 달빛 창가에서) - G-DRAGON, 황정민, 데프콘, 홍진경, 정형돈, 조세호, 기안84, 안성재, 태양, 정해인, 황광희, 임시완, 이수혁, 대성, 코드 쿤스트 (CODE KUNST), CL, 김고은, DAY6 (데이식스), 부석순 (SEVENTEEN), aespa
81위 | Mantra - 제니 (JENNIE)
82위 | Armageddon - aespa
83위 | 봄날 - 방탄소년단
84위 | 너와의 모든 지금 - 재쓰비 (JAESSBEE)
85위 | 녹아내려요 - DAY6 (데이식스)
86위 | Ditto - NewJeans
87위 | LOVE ATTACK - RESCENE (리센느)
88위 | 마음 따라 뛰는 건 멋지지 않아? - TWS (투어스)
89위 | 미안해 미워해 사랑해 - Crush
90위 | 숙녀에게 - 송필근
91위 | Bag Bad Back - RIIZE
92위 | HBD - 세븐틴 (SEVENTEEN)
93위 | 해야 (HEYA) - IVE (아이브)
94위 | 우리들의 블루스 - 임영웅
95위 | Maybe Tomorrow - DAY6 (데이식스)
96위 | Supernatural - NewJeans
97위 | 춘몽 - 현서 (HYUN SEO)
98위 | 살기 위해서 - 순순희
99위 | Dash - PLAVE
100위 | Skyfall (THE 8 Solo) - 세븐틴 (SEVENTEEN)