In [1]:
from IPython.display import display, HTML 
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<b><font size="5" color="red">ch14_웹데이터수집2_동적</font></b>
## 3절. 동적 웹데이터 수집
```
    pip install selenium
```
- Docs : https://www.selenium.dev/documentation/, https://selenium-python.readthedocs.io/

In [27]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.get("http://www.python.org")
elem = driver.find_element(By.NAME, 'q')
elem.clear()
elem.send_keys('pycon')
from selenium.webdriver.common.keys import Keys
elem.send_keys(Keys.RETURN) # enter 효과

In [12]:
result_list = driver.find_elements(By.CSS_SELECTOR, 'li > h3 > a')
for result in result_list:
    print('{} - {}'.format(result.text, result.get_attribute('href')))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon AU 2015 - https://www.python.org/events/python-events/273/
PyCon Australia 2016 - https://www.python.org/events/python-events/357/

In [19]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(driver.page_source, 'html.parser')
result_list = soup.select('li> h3 >a')
for result in result_list:
    print('{} - {}'.format(result.text, result.attrs['href']))

PSF PyCon Trademark Usage Policy - /psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - /events/python-events/378/
PyCon Australia 2013 - /events/python-events/57/
PyCon AU 2019 - /events/python-events/776/
PyCon Australia 2014 - /events/python-events/10/
PyCon Ireland 2012 - /events/python-events/76/
PyCon Ireland 2016 - /events/python-events/429/
PyCon Ireland 2022 - /events/python-events/1320/
PyCon Australia 2014 - /events/python-events/1447/
PyCon Ireland 2024 - /events/python-events/1862/
PyCon APAC 2025 - /events/python-events/1879/
PyCon AU 2018 - /events/python-events/696/
PyCon APAC 2022 - /events/python-events/1216/
PyCon PH 2024 - /events/python-events/1661/
PyCon Ireland 2023 - /events/python-events/1568/
PyCon PL 2014 - /events/python-events/191/
PyCon MY 2015 - /events/python-events/313/
PyCon Ireland 2015 - /events/python-events/333/
PyCon AU 2015 - /events/python-events/273/
PyCon Australia 2016 - /events/python-events/357/

In [18]:
# 셀레니움을 통해 접근한 현재 url
from urllib.parse import urlparse
current_url = driver.current_url
print('현재 주소 : ', current_url)
parse_url = urlparse(current_url)
print('parse_url: ', parse_url)
domain = f'{parse_url.scheme}://{parse_url.netloc}'
print(domain)

현재 주소 :  https://www.python.org/search/?q=pycon&submit=
parse_url:  ParseResult(scheme='https', netloc='www.python.org', path='/search/', params='', query='q=pycon&submit=', fragment='')
https://www.python.org

In [25]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
result_list = soup.select('li> h3 >a')
for result in result_list:
    print('{} - {}'.format(result.text, domain+result.attrs['href']))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon AU 2015 - https://www.python.org/events/python-events/273/
PyCon Australia 2016 - https://www.python.org/events/python-events/357/

In [28]:
driver.close()

## 3.2 예제
### 1) 다음뉴스 검색

In [47]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()
driver.get("http://www.daum.net/")
# input태그를 click
time.sleep(1)
driver.find_element(By.NAME, 'q').click()
query = input('검색하고자 하는 단어는?')
driver.find_element(By.CSS_SELECTOR, 'input[type="text"]').send_keys(query)
driver.find_element(By.CLASS_NAME, 'btn_ksearch').click()
time.sleep(2)
# 뉴스탭 클릭 : ul.list_tab > li
# driver.find_elements(By.CSS_SELECTOR, 'ul.list_tab > li')[3].click()
driver.find_element(By.LINK_TEXT, '뉴스').click()
time.sleep(2)
news_list = []
elems = driver.find_elements(By.CSS_SELECTOR, 'div.item-title > strong.tit-g > a')
for elem in elems:
    title = elem.text
    link = elem.get_attribute('href')
    news_list.append([title, link])
    print(title, link)

검색하고자 하는 단어는?MAGA
[시론] 트럼프 MAGA 정책은 위기이자 기회다 http://v.daum.net/v/20250529002629255
트럼프 사면의 법칙…MAGA 충성하거나 금융범죄자거나 http://v.daum.net/v/20250529112120497
日대표에 ‘MAGA 모자’ 씌운 트럼프, ‘충성 연출’ 논란 http://v.daum.net/v/20250420070848540
Trump’s MAGA trade policy: A crisis, but also an opportunity for Korea http://v.daum.net/v/20250529000350877
'너도 기자냐고? 그러는 네가 가짜야' MAGA 미디어의 역습 [World Now] http://v.daum.net/v/20250428103111009
교황의 맏형은 'MAGA' 지지자…"오바마가 독재 · 인종차별" 주장 http://v.daum.net/v/20250515053302860
‘MAGA 모자’ 中 공장 가보니 원가 4000원… “세계서 여기만 가능” http://v.daum.net/v/20250506005304831
교황 큰 형은 정치적 극우 성향 드러내 온 'MAGA' 지지자 http://v.daum.net/v/20250514170255961
[세계를 가다]MAGA ‘NO’ 푸른색 ‘NO’…“정치대화 금지” 식당 http://v.daum.net/v/20250505195644626
트럼프, 대통령 하면서 가족은 3조 벌었다…MAGA도 "이건 뇌물" http://v.daum.net/v/20250515142011575

In [50]:
# 2page로
page_div = driver.find_element(By.CSS_SELECTOR, 'div.inner_paging')
# print(page_div.text)
next_page = page_div.find_element(By.LINK_TEXT, '2')
next_page.click()

1 2 3 4 5

In [54]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()
driver.get("http://www.daum.net/")
# input태그를 click
time.sleep(1)
driver.find_element(By.NAME, 'q').click()
query = input('검색하고자 하는 단어는?')
driver.find_element(By.CSS_SELECTOR, 'input[type="text"]').send_keys(query)
driver.find_element(By.CLASS_NAME, 'btn_ksearch').click()
time.sleep(2)
# 뉴스탭 클릭 : ul.list_tab > li
# driver.find_elements(By.CSS_SELECTOR, 'ul.list_tab > li')[3].click()
driver.find_element(By.LINK_TEXT, '뉴스').click()
time.sleep(2)
news_list = []
pages = 3
for page in range(1,pages+1):
    elems = driver.find_elements(By.CSS_SELECTOR, 'div.item-title > strong.tit-g > a')
    for elem in elems:
        title = elem.text
        link = elem.get_attribute('href')
        news_list.append([title, link])
        
    # 2page로
    page_div = driver.find_element(By.CSS_SELECTOR, 'div.inner_paging')
    # print(page_div.text)
    next_page = page_div.find_element(By.LINK_TEXT, str(page+1))
    next_page.click()
    time.sleep(1.5)
    print(f'~~ 현재 {page}페이지 데이터를 수집 중입니다~~')
driver.close()
import pandas as pd
df = pd.DataFrame(news_list, columns=['title','link'])
df.to_csv('data/ch14_daum.csv', index=False, encoding='cp949')

검색하고자 하는 단어는?투표율
~~ 현재 1페이지 데이터를 수집 중입니다~~
~~ 현재 2페이지 데이터를 수집 중입니다~~
~~ 현재 3페이지 데이터를 수집 중입니다~~

### 2) 맞춤법 검사기
- 네이버 맞춤법 검사기

In [1]:
# f = open('data/ch14_맞춤법전.txt', 'r', encoding='utf-8')
# text = f.read()
# f.close()

In [3]:
# ch14_맞춤법전.txt를 300자이내로 자르기
with open('data/ch14_맞춤법검사전.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print('총글자 수 :',len(text))
ready_list = [] # 맞춤법 검사할 text 내용(300이자 이내로 list)
while(len(text) > 300):
    temp = text[:300]
    new_line_char_index = temp.rfind('\n')
    print(new_line_char_index)
    ready_list.append(text[:new_line_char_index])
    text = text[new_line_char_index:]
ready_list.append(text)
[ready[:10] for ready in ready_list]

총글자 수 : 1785
242
170
156
204
283
295
136

['안냥하십니까> P ',
 '\n가장 큰 문제는 ',
 '\n또한, 투자자 보',
 '\n운영 방식에서도 ',
 '\n정보의 투명성도 ',
 '\n둘째, 투자자 보',
 '\n넷째, 국내외 사',
 '\n결론적으로, P2']

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time
driver = webdriver.Chrome()

time.sleep(0.5)
driver.get('https://www.naver.com/')
input_elem = driver.find_element(By.CSS_SELECTOR, 'input[name="query"]')
input_elem.send_keys('맞춤법 검사기')
input_elem.send_keys(Keys.RETURN)

time.sleep(0.5)
results ='' # 맞춤법 검사후 내용
textarea = driver.find_element(By.CLASS_NAME, 'txt_gray')
for ready in ready_list:
    time.sleep(2)

    textarea.send_keys(Keys.CONTROL,'a') # control + a
    textarea.send_keys(ready)

    button = driver.find_element(By.CLASS_NAME, 'btn_check')
    button.click()
    time.sleep(2)
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    result = soup.select_one('p._result_text.stand_txt').text
    results += result + '\n\n'
driver.close()

with open('data/ch14_맞춤법점검후.txt', 'w', encoding='utf-8') as f:
    f.write(results)

In [21]:
# ch14_맞춤법점검전.txt를 1000자이내로 자르기
with open('data/ch14_맞춤법검사전.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print('총글자 수 :',len(text))
ready_list = [] # 맞춤법 검사할 text 내용(300이자 이내로 list)
while(len(text) > 1000):
    temp = text[:1000]
    new_line_char_index = temp.rfind('\n')
    ready_list.append(text[:new_line_char_index])
    text = text[new_line_char_index:]
ready_list.append(text)
print('번역할 한글 수:', [len(ready) for ready in ready_list])

총글자 수 : 1016
번역할 한글 수: [932, 84]

In [22]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time

driver = webdriver.Chrome()
time.sleep(0.5)

driver.get('https://www.daum.net/')
input_elem = driver.find_element(By.CSS_SELECTOR, 'input[name="q"]')
input_elem.send_keys('한국어번역기')
input_elem.send_keys(Keys.RETURN)
time.sleep(0.5)

results ='' # 맞춤법 검사후 내용
textarea = driver.find_element(By.CSS_SELECTOR, 'textarea.translate_area.area_item.translate_many')
button = driver.find_element(By.CSS_SELECTOR, 'div.btn_item')

for ready in ready_list:
    time.sleep(2)
    print('~~~ 번역중 ~~~')
    textarea.send_keys(Keys.CONTROL,'a') # control + a
    textarea.send_keys(ready)
    
    button.click()
    time.sleep(2) 
    
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    result = soup.select_one('div.result_area').text
    results += result + '\n\n'
driver.close()

with open('data/ch14_영어번역후.txt', 'w', encoding='utf-8') as f:
    f.write(results)

~~~ 번역중 ~~~
~~~ 번역중 ~~~

### 3) 나혼자 연습
#### 네이버/금융/증권/주가총액

In [17]:
a=[1,2,3]
a.insert(2,'a')
a

[1, 2, 'a', 3]

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import math
import time
import requests
import pandas as pd

driver = webdriver.Chrome() 
driver.get('https://finance.naver.com/sise/sise_market_sum.naver')
time.sleep(0.5) # 초기화면 접근

no_tgl_bxs = len(driver.find_elements(By.CSS_SELECTOR, 'td > input[type="checkbox"]'))
toggle_boxes = [f'option{i}' for i in range(1, no_tgl_bxs+1)] # 체크박스 이름 준비

pageN = 2
max_tgl = 6
item_list = pd.DataFrame([])
for page in range(1,pageN+1):
    page_item_list = []
    for sheet in range(0, math.ceil(no_tgl_bxs/max_tgl)):
        dflt_toggle_boxes = driver.find_elements(By.CSS_SELECTOR, 'td.choice > input[type="checkbox"]')
        [elem.send_keys(Keys.SPACE) for elem in dflt_toggle_boxes]
        time.sleep(0.5) # 디폴트 체크박스 toggle
        
        sheet_toggle_boxes = toggle_boxes[sheet*max_tgl:min((sheet+1)*max_tgl, no_tgl_bxs+1)]
        new_toggle_boxes = [select_box for select_box in sheet_toggle_boxes]
        [driver.find_element(By.ID, box_id).send_keys(Keys.SPACE) for box_id in new_toggle_boxes]
        time.sleep(0.5) # 시트별 새로운 체크박스 toggle
        driver.find_element(By.CSS_SELECTOR, 'div.item_btn > a').click()
        time.sleep(0.5) # 토글 체크후 submit버튼 클릭

        print(f'~~ 현재 {page}페이지 {sheet}시트 데이터를 수집 중입니다~~')

        soup = BeautifulSoup(driver.page_source, 'html.parser')
        table_head = [e.text.strip() for e in soup.select('thead > tr >th')]
        items = soup.select('tbody > tr') # 테이블 헤드 수집
        sheet_item_list = []
        for idx, item in enumerate(items):
            if(item.select_one('td.no')):
                no = item.select_one('td.no').text
                title = item.select_one('a.tltle').text
                price_vals = [e.text.strip() for e in item.select('td.number')]
                if(price_vals[1].strip()=='보합0'):
                    price_vals[1]=['보합',0]
                else:
                    price_vals[1] = [price_vals[1].split('\n')[0], price_vals[1].split('\n')[1].strip()]

                table_head.insert(3, '전일비변동')
                price_vals.insert(0,no), price_vals.insert(1,title),
                price_vals.insert(3,price_vals[1][0]), price_vals.insert(4,price_vals[1][1])
                
                sheet_item_list.append({
                    [f'{e[i]}:{price_vals[i]},' for i, e in enumerate(table_head) if table_head[i]]
                }) # 테이블 내용 수집 
        if sheet == 0:
            page_item_list = pd.DataFrame(sheet_item_list)
        elif sheet < round(no_tgl_bxs/max_tgl):
            page_item_list = pd.concat([page_item_list, pd.DataFrame(sheet_item_list[6:12])], axis=1)
        else: 
            page_item_list = pd.concat([page_item_list, pd.DataFrame(sheet_item_list[6:8])], axis=1)
            # 페이지 내 시트 축적
    item_list = pd.concat([item_list, page_item_list], axis=0) # 페이지 내용 축적
    
    page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
    if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
        page_div.find_element(By.LINK_TEXT, str(page+1)).click()
        time.sleep(1.5) # next page로
    
item_list.to_csv(f'data/naver/fin_gsum_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
item_list.sample(10)

C:\Users\Admin\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (4.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

~~ 현재 1페이지 0시트 데이터를 수집 중입니다~~

IndexError: string index out of range

In [2]:
math.ceil(3.4)

NameError: name 'math' is not defined

In [42]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import time
import requests
import pandas as pd

driver = webdriver.Chrome()
driver.get('https://finance.naver.com/sise/sise_market_sum.naver')
time.sleep(0.5)


new_toggle_boxs = ['option6', 'option12', 'option18', 'option23', 'option24', 'option27']
[driver.find_element(By.ID, box_id).send_keys(Keys.SPACE) for box_id in new_toggle_boxs]
time.sleep(0.5)
driver.find_element(By.CSS_SELECTOR, 'div.item_btn > a').click()
time.sleep(2)
pageN = 10
item_list = []
for page in range(1,pageN+1):
    print(f'~~ 현재 {page}페이지 데이터를 수집 중입니다~~')
#    url = f'https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page={page}'
#    response = requests.get(url)
    soup = BeautifulSoup(driver.page_source, 'html.parser')

#    items = soup.select('td.choice')
#    selected_items = [e.text.strip() for e in items]
    table_head = [e.text.strip() for e in soup.select('thead > tr >th')]
    items = soup.select('tbody > tr')
    for idx, item in enumerate(items):
        if(item.select_one('td.no')):
            no = item.select_one('td.no').text
            title = item.select_one('a.tltle').text
            price_vals = [e.text.strip() for e in item.select('td.number')]
            if(price_vals[1].strip()=='보합0'):
                price_vals[1]=['보합',0]
            else:
                price_vals[1] = [price_vals[1].split('\n')[0], price_vals[1].split('\n')[1].strip()]

            item_list.append({
                table_head[0]:no,
                table_head[1]:title,
                table_head[2]:price_vals[0],
                '전일비변동':price_vals[1][0],
                table_head[3]:price_vals[1][1],
                table_head[4]:price_vals[2],
                table_head[5]:price_vals[3],
                table_head[6]:price_vals[4],
                table_head[7]:price_vals[5],
                table_head[8]:price_vals[6],
                table_head[9]:price_vals[7],
                table_head[10]:price_vals[8],
                table_head[11]:price_vals[9],
            })

    # next page로
    page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
    if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
        page_div.find_element(By.LINK_TEXT, str(page+1)).click()
        time.sleep(1.5)
    
df = pd.DataFrame(item_list)
df.to_csv(f'data/naver/fin_gsum_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
df.sample(10)

~~ 현재 1페이지 데이터를 수집 중입니다~~
~~ 현재 2페이지 데이터를 수집 중입니다~~
~~ 현재 3페이지 데이터를 수집 중입니다~~
~~ 현재 4페이지 데이터를 수집 중입니다~~
~~ 현재 5페이지 데이터를 수집 중입니다~~
~~ 현재 6페이지 데이터를 수집 중입니다~~
~~ 현재 7페이지 데이터를 수집 중입니다~~
~~ 현재 8페이지 데이터를 수집 중입니다~~
~~ 현재 9페이지 데이터를 수집 중입니다~~
~~ 현재 10페이지 데이터를 수집 중입니다~~

,N,종목명,현재가,전일비변동,전일비,등락률,액면가,주당순이익,PER,ROE,ROA,PBR,유보율
198,199,SNT다이내믹스,"44,900",상승,"2,900",+6.90%,"2,500","3,038",14.78,12.90,9.20,1.28,910.8
412,413,풀무원,"12,450",하락,200,-1.58%,500,820,15.18,11.40,1.53,1.55,647.9
212,213,TIGER 미국30년국채커버드콜액티브(H),"7,885",하락,45,-0.57%,0,N/A,N/A,N/A,N/A,N/A,N/A
440,441,KODEX 미국반도체,"22,300",하락,640,-2.79%,0,N/A,N/A,N/A,N/A,N/A,N/A
405,406,KODEX 26-12 회사채(AA-이상)액티브,"10,795",보합,0,0.00%,0,N/A,N/A,N/A,N/A,N/A,N/A
46,47,LIG넥스원,"447,500",상승,"18,500",+4.31%,"5,000","11,153",40.12,19.59,4.36,7.85,953.9
64,65,HD현대미포,"193,700",상승,200,+0.10%,"5,000","3,822",50.68,5.25,2.26,3.73,791.6
42,43,하이브,"272,000",상승,"6,000",+2.26%,500,"1,256",216.56,0.31,-0.06,3.44,"14,580.2"
457,458,삼성FN리츠,"4,620",상승,5,+0.11%,500,29,159.31,0.66,0.32,1.01,813.9
293,294,빙그레,"88,400",하락,"2,100",-2.32%,"5,000","9,794",9.03,15.14,10.90,1.11,"1,399.0"

#### 네이버/금융/증권/배당

In [43]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import time
import requests
import pandas as pd

driver = webdriver.Chrome()
driver.get('https://finance.naver.com/sise/dividend_list.naver')
time.sleep(0.5)
soup = BeautifulSoup(driver.page_source, 'html.parser')

table_head = [e.text.strip() for e in soup.select('thead > tr > th')]
table_head[9] = '과거3년배당금_Max'
driver.find_element(By.LINK_TEXT, '배당금').click()
time.sleep(2)

pageN = 10
item_list = []
for page in range(1,pageN+1):
    print(f'~~ 현재 {page}페이지 데이터를 수집 중입니다~~')

    items = soup.select('table.type_1.tb_ty> tbody > tr')
    for idx, item in enumerate(items):
        if(item.text.strip()):
            price_vals = [e.text.strip().replace(',','').replace('-','0') for e in item.select('td')]
            price_vals.insert(9, max(price_vals[9:12]))
            
            item_list.append({table_head[i]:e for i, e in enumerate(price_vals)})

    # next page로
    page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
    if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
        page_div.find_element(By.LINK_TEXT, str(page+1)).click()
        time.sleep(1.5)
    
df = pd.DataFrame(item_list)
df.to_csv(f'data/naver/fin_div_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
df.sample(10)

~~ 현재 1페이지 데이터를 수집 중입니다~~
~~ 현재 2페이지 데이터를 수집 중입니다~~
~~ 현재 3페이지 데이터를 수집 중입니다~~
~~ 현재 4페이지 데이터를 수집 중입니다~~
~~ 현재 5페이지 데이터를 수집 중입니다~~
~~ 현재 6페이지 데이터를 수집 중입니다~~
~~ 현재 7페이지 데이터를 수집 중입니다~~
~~ 현재 8페이지 데이터를 수집 중입니다~~
~~ 현재 9페이지 데이터를 수집 중입니다~~
~~ 현재 10페이지 데이터를 수집 중입니다~~

,종목명,현재가,기준월,배당금,수익률(%),배당성향(%),ROE(%),PER(배),PBR(배),과거3년배당금_Max,1년전,2년전,3년전
46,유아이엘,3685,24.12,270,7.33,28.64,16.63,3.77,0.56,0,0,0,0
126,동국씨엠,6320,25.03,500,7.91,23.40,6.45,2.79,0.17,100,100,0,0
170,현대차3우B,146400,25.02,12050,8.23,25.13,12.43,4.60,0.51,7050,11450,7050,5050
490,케이카,15360,24.12,1150,7.49,126.03,19.09,14.04,2.73,760,760,760,750
44,기아,88400,25.03,6500,7.35,26.18,19.09,4.12,0.71,5600,5600,3500,3000
233,KISCO홀딩스,23450,24.12,1800,7.68,70.13,2.82,9.94,0.21,900,900,600,400
390,케이카,15360,24.12,1150,7.49,126.03,19.09,14.04,2.73,760,760,760,750
84,조선내화,13030,24.12,1000,7.68,203.40,2.68,31.46,0.83,0,0,0,0
477,도이치모터스,4810,24.12,380,7.90,0224.96,01.22,028.41,0.33,370,370,360,350
411,NH올원리츠,3675,24.12,340,9.25,0830.66,00.56,0135.96,0.80,316,288,316,106

In [29]:
a=['12,000','3','4']
max(a)
# str(sum([float(e.replace(',','')) for e in a]))

'4'